### ISSUE TITLE
Does not work in wine

### ISSUE THREAD

**Issue by Weissnix4711** [tomrhollis/vellum-for-EZ#3]
I don't have time to troubleshoot it right now, but it seems this won't run under wine.

**Comment by tomrhollis** [comment]
Unfortunately I don't have the bandwidth to add another testing environment, but if there are simple things I could do to make it more likely to work in wine, I'd be happy to implement those if someone sends me that information. Otherwise when I do the next phase of features I will update the documentation to state that wine is unsupported.

Leaving this open until then

**Comment by clarkx86** [comment]
@Weissnix4711 It's because Wine doesn't provide an implementation of the .NET Core runtime, only .NET Framework as Mono. You would either need to install the .NET Core 3 or @tomrhollis would need to provide a self-contained, bundled release.
I could not seem to find an .NET Core runtime install script in `winetricks`, so I grabbed the latest installer from [here](https://dotnet.microsoft.com/download/dotnet-core/3.1) ([x64](https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.302-windows-x64-installer) or [x86](https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.302-windows-x86-installer)). The setup completed successfully and after running vellum again using `WINEDEBUG=-all wine vellum.exe`, it successfully started!
I recommend using `WINEDEBUG=-all` so you see nothing but vellums output.

**Comment by tomrhollis** [comment]
The readme included with the release does contain instructions to install .NET Core, but if that's a pain when using docker-wine I could do a self-contained release and see how that goes.  @Weissnix4711 let me know, or if .NET isn't the issue please provide more info on how it's failing.

**Comment by tomrhollis** [comment]
Closing for now, let me know if this is still something to look into
